# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

target 'SimpleMoviePlayerExample' do
  use_frameworks!

  # Pods for SimpleMoviePlayerExample

  # UI Libraries
  pod 'Cosmos', '~> 23.0'
  pod 'ActiveLabel'
  pod 'GrowingTextView', '0.7.2'  
  pod 'EasyTipView', '~> 2.1'
  pod 'FontAwesome.swift'
  pod 'AnimatedCollectionViewLayout'

  # RxSwift & RxCocoa
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

  target 'SimpleMoviePlayerExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.2.0'
    pod 'RxTest', '6.2.0'
  end

  target 'SimpleMoviePlayerExampleUITests' do
    # Pods for testing
  end

end
