# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

target 'SimpleMoviePlayerExample' do
  use_frameworks!

  # Pods for SimpleMoviePlayerExample
  #pod 'Cosmos', '~> 23.0'
  #pod 'ActiveLabel'
  #pod 'GrowingTextView', '0.7.2'  

  target 'SimpleMoviePlayerExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpleMoviePlayerExampleUITests' do
    # Pods for testing
  end

end
